development:
  adapter: postgresql
  encoding: unicode
  database: secret_santa_development
  host: localhost
  pool: 5
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_USER_PASS'] %>

test:
  adapter: postgresql
  encoding: unicode
  database: secret_santa_test
  host: localhost
  pool: 5
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_USER_PASS'] %>

production:
  adapter: postgresql
  encoding: unicode
  database: secret_santa_production
  pool: 5
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_USER_PASS'] %>
